export const ADD_STRING = 'ADD_STRING';
export const ADD_STRING_SUCCESS = 'ADD_STRING_SUCCESS';
export const ADD_STRING_FAILURE = 'ADD_STRING_FAILURE';
export const ADD_STRING_RESET = 'ADD_STRING_RESET';
